version: '3.9'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  # app:
  #   links:
  #     - database_ignite
  #   depends_on:
  #     - database_ignite
  #   build: .
  #   container_name: rentx
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app

volumes:
  pgdata:
    driver: local
